# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hydrabot.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("HydraBot")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/HydraBot/media/Media/watermelon_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.MainTabs.setFont(font)
        self.MainTabs.setObjectName("MainTabs")
        self.LiveViewTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LiveViewTab.sizePolicy().hasHeightForWidth())
        self.LiveViewTab.setSizePolicy(sizePolicy)
        self.LiveViewTab.setObjectName("LiveViewTab")
        self.gridLayout = QtWidgets.QGridLayout(self.LiveViewTab)
        self.gridLayout.setObjectName("gridLayout")
        self.dBackgroundLabel = QtWidgets.QLabel(self.LiveViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dBackgroundLabel.sizePolicy().hasHeightForWidth())
        self.dBackgroundLabel.setSizePolicy(sizePolicy)
        self.dBackgroundLabel.setStyleSheet("border-image: url(:/HydraBot/Media/Hydra Fluor crop.jpg);")
        self.dBackgroundLabel.setText("")
        self.dBackgroundLabel.setScaledContents(False)
        self.dBackgroundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dBackgroundLabel.setObjectName("dBackgroundLabel")
        self.gridLayout.addWidget(self.dBackgroundLabel, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoSurfaceLayout = QtWidgets.QHBoxLayout()
        self.videoSurfaceLayout.setObjectName("videoSurfaceLayout")
        self.CamPreviewLabel = QtWidgets.QLabel(self.LiveViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CamPreviewLabel.sizePolicy().hasHeightForWidth())
        self.CamPreviewLabel.setSizePolicy(sizePolicy)
        self.CamPreviewLabel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.CamPreviewLabel.setText("")
        self.CamPreviewLabel.setScaledContents(False)
        self.CamPreviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CamPreviewLabel.setObjectName("CamPreviewLabel")
        self.videoSurfaceLayout.addWidget(self.CamPreviewLabel)
        self.verticalLayout.addLayout(self.videoSurfaceLayout)
        self.previewCheckBox = QtWidgets.QCheckBox(self.LiveViewTab)
        self.previewCheckBox.setChecked(True)
        self.previewCheckBox.setObjectName("previewCheckBox")
        self.verticalLayout.addWidget(self.previewCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.initCameraButton = QtWidgets.QPushButton(self.LiveViewTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setKerning(False)
        self.initCameraButton.setFont(font)
        self.initCameraButton.setObjectName("initCameraButton")
        self.horizontalLayout_3.addWidget(self.initCameraButton)
        self.scanQRButton = QtWidgets.QPushButton(self.LiveViewTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setKerning(False)
        self.scanQRButton.setFont(font)
        self.scanQRButton.setObjectName("scanQRButton")
        self.horizontalLayout_3.addWidget(self.scanQRButton)
        self.scanWellsButton = QtWidgets.QPushButton(self.LiveViewTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setKerning(False)
        self.scanWellsButton.setFont(font)
        self.scanWellsButton.setObjectName("scanWellsButton")
        self.horizontalLayout_3.addWidget(self.scanWellsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exposureModeComboBox = QtWidgets.QComboBox(self.LiveViewTab)
        self.exposureModeComboBox.setObjectName("exposureModeComboBox")
        self.horizontalLayout_4.addWidget(self.exposureModeComboBox)
        self.camShutterBox = QtWidgets.QDoubleSpinBox(self.LiveViewTab)
        self.camShutterBox.setMinimum(-8192.0)
        self.camShutterBox.setMaximum(8192.0)
        self.camShutterBox.setObjectName("camShutterBox")
        self.horizontalLayout_4.addWidget(self.camShutterBox)
        self.camPropLineEdit = QtWidgets.QLineEdit(self.LiveViewTab)
        self.camPropLineEdit.setObjectName("camPropLineEdit")
        self.horizontalLayout_4.addWidget(self.camPropLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 50)
        self.gridLayout.setColumnStretch(1, 50)
        self.MainTabs.addTab(self.LiveViewTab, "")
        self.OT2Tab = QtWidgets.QWidget()
        self.OT2Tab.setObjectName("OT2Tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.OT2Tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.OT2StackedWidget = QtWidgets.QStackedWidget(self.OT2Tab)
        self.OT2StackedWidget.setObjectName("OT2StackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ot2MoveCameraPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2MoveCameraPushButton.setObjectName("ot2MoveCameraPushButton")
        self.gridLayout_5.addWidget(self.ot2MoveCameraPushButton, 2, 0, 1, 1)
        self.scanDeckPushButton = QtWidgets.QPushButton(self.page_2)
        self.scanDeckPushButton.setObjectName("scanDeckPushButton")
        self.gridLayout_5.addWidget(self.scanDeckPushButton, 1, 0, 1, 1)
        self.platesOnDeckTableWidget = QtWidgets.QTableWidget(self.page_2)
        self.platesOnDeckTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.platesOnDeckTableWidget.setAlternatingRowColors(True)
        self.platesOnDeckTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.platesOnDeckTableWidget.setRowCount(4)
        self.platesOnDeckTableWidget.setColumnCount(3)
        self.platesOnDeckTableWidget.setObjectName("platesOnDeckTableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.platesOnDeckTableWidget.setItem(3, 2, item)
        self.platesOnDeckTableWidget.horizontalHeader().setVisible(False)
        self.platesOnDeckTableWidget.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.platesOnDeckTableWidget, 1, 1, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ot2ServerConnectPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2ServerConnectPushButton.setObjectName("ot2ServerConnectPushButton")
        self.horizontalLayout_16.addWidget(self.ot2ServerConnectPushButton)
        self.ot2ConnectRobotPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2ConnectRobotPushButton.setObjectName("ot2ConnectRobotPushButton")
        self.horizontalLayout_16.addWidget(self.ot2ConnectRobotPushButton)
        self.ot2ServerDisconnectPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2ServerDisconnectPushButton.setEnabled(False)
        self.ot2ServerDisconnectPushButton.setObjectName("ot2ServerDisconnectPushButton")
        self.horizontalLayout_16.addWidget(self.ot2ServerDisconnectPushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 0, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ot2SlotComboBox = QtWidgets.QComboBox(self.page_2)
        self.ot2SlotComboBox.setObjectName("ot2SlotComboBox")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.ot2SlotComboBox.addItem("")
        self.horizontalLayout_18.addWidget(self.ot2SlotComboBox)
        self.ot2WellComboBox = QtWidgets.QComboBox(self.page_2)
        self.ot2WellComboBox.setObjectName("ot2WellComboBox")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.ot2WellComboBox.addItem("")
        self.horizontalLayout_18.addWidget(self.ot2WellComboBox)
        self.ot2HeightDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.page_2)
        self.ot2HeightDoubleSpinBox.setMinimum(-1.0)
        self.ot2HeightDoubleSpinBox.setMaximum(5.0)
        self.ot2HeightDoubleSpinBox.setSingleStep(0.05)
        self.ot2HeightDoubleSpinBox.setObjectName("ot2HeightDoubleSpinBox")
        self.horizontalLayout_18.addWidget(self.ot2HeightDoubleSpinBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 2, 1, 1, 1)
        self.hostnameLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.hostnameLineEdit.setObjectName("hostnameLineEdit")
        self.gridLayout_5.addWidget(self.hostnameLineEdit, 0, 0, 1, 1)
        self.ot2HomePushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2HomePushButton.setObjectName("ot2HomePushButton")
        self.gridLayout_5.addWidget(self.ot2HomePushButton, 3, 0, 1, 1)
        self.ot2CommandLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.ot2CommandLineEdit.setObjectName("ot2CommandLineEdit")
        self.gridLayout_5.addWidget(self.ot2CommandLineEdit, 4, 1, 1, 1)
        self.ot2SendCommandPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2SendCommandPushButton.setObjectName("ot2SendCommandPushButton")
        self.gridLayout_5.addWidget(self.ot2SendCommandPushButton, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ot2LightsOnPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2LightsOnPushButton.setObjectName("ot2LightsOnPushButton")
        self.horizontalLayout_5.addWidget(self.ot2LightsOnPushButton)
        self.ot2LightsOffPushButton = QtWidgets.QPushButton(self.page_2)
        self.ot2LightsOffPushButton.setObjectName("ot2LightsOffPushButton")
        self.horizontalLayout_5.addWidget(self.ot2LightsOffPushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.OT2StackedWidget.addWidget(self.page_2)
        self.debugTerminalPage = QtWidgets.QWidget()
        self.debugTerminalPage.setObjectName("debugTerminalPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.debugTerminalPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.debugCommandsPlainTextEdit = QtWidgets.QPlainTextEdit(self.debugTerminalPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.debugCommandsPlainTextEdit.setFont(font)
        self.debugCommandsPlainTextEdit.setReadOnly(True)
        self.debugCommandsPlainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.debugCommandsPlainTextEdit.setObjectName("debugCommandsPlainTextEdit")
        self.gridLayout_4.addWidget(self.debugCommandsPlainTextEdit, 0, 0, 1, 1)
        self.debugOutputPlainTextEdit = QtWidgets.QPlainTextEdit(self.debugTerminalPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.debugOutputPlainTextEdit.setFont(font)
        self.debugOutputPlainTextEdit.setReadOnly(True)
        self.debugOutputPlainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.debugOutputPlainTextEdit.setObjectName("debugOutputPlainTextEdit")
        self.gridLayout_4.addWidget(self.debugOutputPlainTextEdit, 0, 1, 1, 1)
        self.debugCommandLineEdit = QtWidgets.QLineEdit(self.debugTerminalPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.debugCommandLineEdit.setFont(font)
        self.debugCommandLineEdit.setObjectName("debugCommandLineEdit")
        self.gridLayout_4.addWidget(self.debugCommandLineEdit, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.debugClearPushButton = QtWidgets.QPushButton(self.debugTerminalPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debugClearPushButton.sizePolicy().hasHeightForWidth())
        self.debugClearPushButton.setSizePolicy(sizePolicy)
        self.debugClearPushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.debugClearPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.debugClearPushButton.setObjectName("debugClearPushButton")
        self.horizontalLayout_15.addWidget(self.debugClearPushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
        self.OT2StackedWidget.addWidget(self.debugTerminalPage)
        self.gridLayout_3.addWidget(self.OT2StackedWidget, 0, 0, 1, 1)
        self.MainTabs.addTab(self.OT2Tab, "")
        self.PlateTab = QtWidgets.QWidget()
        self.PlateTab.setObjectName("PlateTab")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.PlateTab)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PlateFunctionsTab = QtWidgets.QTabWidget(self.PlateTab)
        self.PlateFunctionsTab.setObjectName("PlateFunctionsTab")
        self.ManifestTab = QtWidgets.QWidget()
        self.ManifestTab.setObjectName("ManifestTab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.ManifestTab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.plateManifestTreeWidget = QtWidgets.QTreeWidget(self.ManifestTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plateManifestTreeWidget.setFont(font)
        self.plateManifestTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.plateManifestTreeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plateManifestTreeWidget.setAlternatingRowColors(True)
        self.plateManifestTreeWidget.setIconSize(QtCore.QSize(24, 24))
        self.plateManifestTreeWidget.setAnimated(True)
        self.plateManifestTreeWidget.setAllColumnsShowFocus(True)
        self.plateManifestTreeWidget.setWordWrap(True)
        self.plateManifestTreeWidget.setColumnCount(3)
        self.plateManifestTreeWidget.setObjectName("plateManifestTreeWidget")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plateManifestTreeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plateManifestTreeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plateManifestTreeWidget.headerItem().setFont(2, font)
        self.plateManifestTreeWidget.header().setDefaultSectionSize(250)
        self.plateManifestTreeWidget.header().setHighlightSections(True)
        self.plateManifestTreeWidget.header().setMinimumSectionSize(100)
        self.horizontalLayout_14.addWidget(self.plateManifestTreeWidget)
        self.PlateFunctionsTab.addTab(self.ManifestTab, "")
        self.AddPlateTab = QtWidgets.QWidget()
        self.AddPlateTab.setObjectName("AddPlateTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AddPlateTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.AddPlateTab)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_24 = QtWidgets.QLabel(self.AddPlateTab)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_27.addWidget(self.label_24)
        self.plateIDLineEdit = QtWidgets.QLineEdit(self.AddPlateTab)
        self.plateIDLineEdit.setMaxLength(32)
        self.plateIDLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plateIDLineEdit.setObjectName("plateIDLineEdit")
        self.horizontalLayout_27.addWidget(self.plateIDLineEdit)
        self.createPlateButton = QtWidgets.QPushButton(self.AddPlateTab)
        self.createPlateButton.setObjectName("createPlateButton")
        self.horizontalLayout_27.addWidget(self.createPlateButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.QRDispLabel = QtWidgets.QLabel(self.AddPlateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QRDispLabel.sizePolicy().hasHeightForWidth())
        self.QRDispLabel.setSizePolicy(sizePolicy)
        self.QRDispLabel.setMinimumSize(QtCore.QSize(0, 360))
        self.QRDispLabel.setText("")
        self.QRDispLabel.setObjectName("QRDispLabel")
        self.horizontalLayout_26.addWidget(self.QRDispLabel)
        self.plateListWidget = QtWidgets.QListWidget(self.AddPlateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plateListWidget.sizePolicy().hasHeightForWidth())
        self.plateListWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.plateListWidget.setFont(font)
        self.plateListWidget.setStyleSheet("padding: 1px;")
        self.plateListWidget.setAlternatingRowColors(True)
        self.plateListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.plateListWidget.setObjectName("plateListWidget")
        self.horizontalLayout_26.addWidget(self.plateListWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.emailLineEdit = QtWidgets.QLineEdit(self.AddPlateTab)
        self.emailLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.horizontalLayout_24.addWidget(self.emailLineEdit)
        self.passLineEdit = QtWidgets.QLineEdit(self.AddPlateTab)
        self.passLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passLineEdit.setObjectName("passLineEdit")
        self.horizontalLayout_24.addWidget(self.passLineEdit)
        self.emailToLineEdit = QtWidgets.QLineEdit(self.AddPlateTab)
        self.emailToLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.emailToLineEdit.setObjectName("emailToLineEdit")
        self.horizontalLayout_24.addWidget(self.emailToLineEdit)
        self.sendEmailButton = QtWidgets.QPushButton(self.AddPlateTab)
        self.sendEmailButton.setObjectName("sendEmailButton")
        self.horizontalLayout_24.addWidget(self.sendEmailButton)
        self.emailStatusLabel = QtWidgets.QLabel(self.AddPlateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailStatusLabel.sizePolicy().hasHeightForWidth())
        self.emailStatusLabel.setSizePolicy(sizePolicy)
        self.emailStatusLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.emailStatusLabel.setText("")
        self.emailStatusLabel.setObjectName("emailStatusLabel")
        self.horizontalLayout_24.addWidget(self.emailStatusLabel)
        spacerItem2 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.AddPlateTab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.SMTPLineEdit = QtWidgets.QLineEdit(self.AddPlateTab)
        self.SMTPLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SMTPLineEdit.setObjectName("SMTPLineEdit")
        self.horizontalLayout_25.addWidget(self.SMTPLineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.PlateFunctionsTab.addTab(self.AddPlateTab, "")
        self.horizontalLayout_19.addWidget(self.PlateFunctionsTab)
        self.MainTabs.addTab(self.PlateTab, "")
        self.AnimalsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnimalsTab.sizePolicy().hasHeightForWidth())
        self.AnimalsTab.setSizePolicy(sizePolicy)
        self.AnimalsTab.setObjectName("AnimalsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AnimalsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.AnimalsTab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.lineEdit = QtWidgets.QLineEdit(self.AnimalsTab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_13.addWidget(self.lineEdit)
        self.searchToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/HydraBot/Media/search_blue_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchToolButton.setIcon(icon1)
        self.searchToolButton.setIconSize(QtCore.QSize(48, 48))
        self.searchToolButton.setObjectName("searchToolButton")
        self.horizontalLayout_13.addWidget(self.searchToolButton)
        spacerItem4 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_19 = QtWidgets.QLabel(self.AnimalsTab)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.addStockToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/HydraBot/Media/stock_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addStockToolButton.setIcon(icon2)
        self.addStockToolButton.setIconSize(QtCore.QSize(48, 48))
        self.addStockToolButton.setObjectName("addStockToolButton")
        self.horizontalLayout_13.addWidget(self.addStockToolButton)
        self.addAnimalToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        self.addAnimalToolButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/HydraBot/Media/watermelon_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAnimalToolButton.setIcon(icon3)
        self.addAnimalToolButton.setIconSize(QtCore.QSize(48, 48))
        self.addAnimalToolButton.setObjectName("addAnimalToolButton")
        self.horizontalLayout_13.addWidget(self.addAnimalToolButton)
        self.addColonyToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        self.addColonyToolButton.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/HydraBot/Media/fishbowl_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addColonyToolButton.setIcon(icon4)
        self.addColonyToolButton.setIconSize(QtCore.QSize(48, 48))
        self.addColonyToolButton.setObjectName("addColonyToolButton")
        self.horizontalLayout_13.addWidget(self.addColonyToolButton)
        self.addEventToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        self.addEventToolButton.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/HydraBot/Media/event_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEventToolButton.setIcon(icon5)
        self.addEventToolButton.setIconSize(QtCore.QSize(48, 48))
        self.addEventToolButton.setObjectName("addEventToolButton")
        self.horizontalLayout_13.addWidget(self.addEventToolButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.dataToolButton = QtWidgets.QToolButton(self.AnimalsTab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/HydraBot/Media/settings_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataToolButton.setIcon(icon6)
        self.dataToolButton.setIconSize(QtCore.QSize(48, 48))
        self.dataToolButton.setObjectName("dataToolButton")
        self.horizontalLayout_13.addWidget(self.dataToolButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.databaseSplitter = QtWidgets.QSplitter(self.AnimalsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseSplitter.sizePolicy().hasHeightForWidth())
        self.databaseSplitter.setSizePolicy(sizePolicy)
        self.databaseSplitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.databaseSplitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.databaseSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.databaseSplitter.setOpaqueResize(True)
        self.databaseSplitter.setChildrenCollapsible(True)
        self.databaseSplitter.setObjectName("databaseSplitter")
        self.databaseTreeWidget = QtWidgets.QTreeWidget(self.databaseSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseTreeWidget.sizePolicy().hasHeightForWidth())
        self.databaseTreeWidget.setSizePolicy(sizePolicy)
        self.databaseTreeWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseTreeWidget.setFont(font)
        self.databaseTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.databaseTreeWidget.setStyleSheet("padding: 1px;")
        self.databaseTreeWidget.setAlternatingRowColors(True)
        self.databaseTreeWidget.setIconSize(QtCore.QSize(24, 24))
        self.databaseTreeWidget.setAnimated(True)
        self.databaseTreeWidget.setAllColumnsShowFocus(True)
        self.databaseTreeWidget.setWordWrap(True)
        self.databaseTreeWidget.setColumnCount(4)
        self.databaseTreeWidget.setObjectName("databaseTreeWidget")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseTreeWidget.headerItem().setFont(0, font)
        self.databaseTreeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseTreeWidget.headerItem().setFont(1, font)
        self.databaseTreeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseTreeWidget.headerItem().setFont(2, font)
        self.databaseTreeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseTreeWidget.headerItem().setFont(3, font)
        self.databaseTreeWidget.header().setDefaultSectionSize(200)
        self.databaseTreeWidget.header().setHighlightSections(True)
        self.databaseTreeWidget.header().setMinimumSectionSize(100)
        self.databaseTreeWidget.header().setStretchLastSection(False)
        self.databaseImageLabel = QtWidgets.QLabel(self.databaseSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseImageLabel.sizePolicy().hasHeightForWidth())
        self.databaseImageLabel.setSizePolicy(sizePolicy)
        self.databaseImageLabel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.databaseImageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.databaseImageLabel.setText("")
        self.databaseImageLabel.setPixmap(QtGui.QPixmap(":/HydraBot/media/Media/Hydra Fluor crop.jpg"))
        self.databaseImageLabel.setScaledContents(False)
        self.databaseImageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.databaseImageLabel.setObjectName("databaseImageLabel")
        self.verticalLayout_3.addWidget(self.databaseSplitter)
        self.MainTabs.addTab(self.AnimalsTab, "")
        self.SnapTab = QtWidgets.QWidget()
        self.SnapTab.setObjectName("SnapTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SnapTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SnapLabel = QtWidgets.QLabel(self.SnapTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(75)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SnapLabel.sizePolicy().hasHeightForWidth())
        self.SnapLabel.setSizePolicy(sizePolicy)
        self.SnapLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.SnapLabel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.SnapLabel.setText("")
        self.SnapLabel.setScaledContents(False)
        self.SnapLabel.setObjectName("SnapLabel")
        self.horizontalLayout_2.addWidget(self.SnapLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.snap_reprocess_button = QtWidgets.QPushButton(self.SnapTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_reprocess_button.sizePolicy().hasHeightForWidth())
        self.snap_reprocess_button.setSizePolicy(sizePolicy)
        self.snap_reprocess_button.setObjectName("snap_reprocess_button")
        self.verticalLayout_2.addWidget(self.snap_reprocess_button)
        self.snap_param_1 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_1.setMaximum(10000)
        self.snap_param_1.setProperty("value", 41)
        self.snap_param_1.setObjectName("snap_param_1")
        self.verticalLayout_2.addWidget(self.snap_param_1)
        self.snap_param_2 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_2.setMinimum(-10)
        self.snap_param_2.setMaximum(10000)
        self.snap_param_2.setProperty("value", -5)
        self.snap_param_2.setObjectName("snap_param_2")
        self.verticalLayout_2.addWidget(self.snap_param_2)
        self.snap_param_3 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_3.setMinimum(1)
        self.snap_param_3.setMaximum(16)
        self.snap_param_3.setProperty("value", 3)
        self.snap_param_3.setObjectName("snap_param_3")
        self.verticalLayout_2.addWidget(self.snap_param_3)
        self.snap_param_4 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_4.setMinimum(1)
        self.snap_param_4.setObjectName("snap_param_4")
        self.verticalLayout_2.addWidget(self.snap_param_4)
        self.snap_param_5 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_5.setMinimum(1)
        self.snap_param_5.setMaximum(1000)
        self.snap_param_5.setProperty("value", 30)
        self.snap_param_5.setObjectName("snap_param_5")
        self.verticalLayout_2.addWidget(self.snap_param_5)
        self.snap_param_6 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_6.setMinimum(1)
        self.snap_param_6.setMaximum(1000)
        self.snap_param_6.setProperty("value", 250)
        self.snap_param_6.setObjectName("snap_param_6")
        self.verticalLayout_2.addWidget(self.snap_param_6)
        self.snap_param_7 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_7.setMinimum(1)
        self.snap_param_7.setMaximum(1000)
        self.snap_param_7.setProperty("value", 380)
        self.snap_param_7.setObjectName("snap_param_7")
        self.verticalLayout_2.addWidget(self.snap_param_7)
        self.snap_param_8 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_8.setMinimum(1)
        self.snap_param_8.setMaximum(1000)
        self.snap_param_8.setProperty("value", 485)
        self.snap_param_8.setObjectName("snap_param_8")
        self.verticalLayout_2.addWidget(self.snap_param_8)
        self.snap_param_9 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_9.setMaximum(1000)
        self.snap_param_9.setProperty("value", 935)
        self.snap_param_9.setObjectName("snap_param_9")
        self.verticalLayout_2.addWidget(self.snap_param_9)
        self.snap_param_10 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_10.setMinimum(1)
        self.snap_param_10.setMaximum(20)
        self.snap_param_10.setObjectName("snap_param_10")
        self.verticalLayout_2.addWidget(self.snap_param_10)
        self.snap_param_11 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_11.setMinimum(1)
        self.snap_param_11.setMaximum(499)
        self.snap_param_11.setSingleStep(2)
        self.snap_param_11.setProperty("value", 11)
        self.snap_param_11.setObjectName("snap_param_11")
        self.verticalLayout_2.addWidget(self.snap_param_11)
        self.snap_param_12 = QtWidgets.QSpinBox(self.SnapTab)
        self.snap_param_12.setMinimum(0)
        self.snap_param_12.setMaximum(1)
        self.snap_param_12.setSingleStep(2)
        self.snap_param_12.setProperty("value", 1)
        self.snap_param_12.setObjectName("snap_param_12")
        self.verticalLayout_2.addWidget(self.snap_param_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.scansLabel = QtWidgets.QLabel(self.SnapTab)
        self.scansLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.scansLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scansLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.scansLabel.setObjectName("scansLabel")
        self.horizontalLayout_2.addWidget(self.scansLabel)
        self.MainTabs.addTab(self.SnapTab, "")
        self.ControlsTab = QtWidgets.QWidget()
        self.ControlsTab.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlsTab.sizePolicy().hasHeightForWidth())
        self.ControlsTab.setSizePolicy(sizePolicy)
        self.ControlsTab.setObjectName("ControlsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ControlsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MainTabs.addTab(self.ControlsTab, "")
        self.horizontalLayout.addWidget(self.MainTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainTabs.setCurrentIndex(0)
        self.OT2StackedWidget.setCurrentIndex(0)
        self.PlateFunctionsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.previewCheckBox.setText(_translate("MainWindow", "Show Preview"))
        self.initCameraButton.setText(_translate("MainWindow", "Init Camera"))
        self.scanQRButton.setText(_translate("MainWindow", "Scan QR"))
        self.scanWellsButton.setText(_translate("MainWindow", "Scan Well"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.LiveViewTab), _translate("MainWindow", "Live View"))
        self.ot2MoveCameraPushButton.setText(_translate("MainWindow", " Move Camera To: "))
        self.scanDeckPushButton.setText(_translate("MainWindow", " Scan Deck "))
        __sortingEnabled = self.platesOnDeckTableWidget.isSortingEnabled()
        self.platesOnDeckTableWidget.setSortingEnabled(False)
        item = self.platesOnDeckTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "10"))
        item = self.platesOnDeckTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "11"))
        item = self.platesOnDeckTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "TRASH"))
        item = self.platesOnDeckTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "7"))
        item = self.platesOnDeckTableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "8"))
        item = self.platesOnDeckTableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "9"))
        item = self.platesOnDeckTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.platesOnDeckTableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "5"))
        item = self.platesOnDeckTableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "6"))
        item = self.platesOnDeckTableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.platesOnDeckTableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.platesOnDeckTableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "3"))
        self.platesOnDeckTableWidget.setSortingEnabled(__sortingEnabled)
        self.ot2ServerConnectPushButton.setText(_translate("MainWindow", " Connect "))
        self.ot2ConnectRobotPushButton.setText(_translate("MainWindow", " Engage Robot Movement "))
        self.ot2ServerDisconnectPushButton.setText(_translate("MainWindow", " Disconnect "))
        self.ot2SlotComboBox.setItemText(0, _translate("MainWindow", "Slot 1"))
        self.ot2SlotComboBox.setItemText(1, _translate("MainWindow", "Slot 2"))
        self.ot2SlotComboBox.setItemText(2, _translate("MainWindow", "Slot 3"))
        self.ot2SlotComboBox.setItemText(3, _translate("MainWindow", "Slot 4"))
        self.ot2SlotComboBox.setItemText(4, _translate("MainWindow", "Slot 5"))
        self.ot2SlotComboBox.setItemText(5, _translate("MainWindow", "Slot 6"))
        self.ot2SlotComboBox.setItemText(6, _translate("MainWindow", "Slot 7"))
        self.ot2SlotComboBox.setItemText(7, _translate("MainWindow", "Slot 8"))
        self.ot2SlotComboBox.setItemText(8, _translate("MainWindow", "Slot 9"))
        self.ot2SlotComboBox.setItemText(9, _translate("MainWindow", "Slot 10"))
        self.ot2SlotComboBox.setItemText(10, _translate("MainWindow", "Slot 11"))
        self.ot2SlotComboBox.setItemText(11, _translate("MainWindow", "Trash"))
        self.ot2WellComboBox.setItemText(0, _translate("MainWindow", "QR"))
        self.ot2WellComboBox.setItemText(1, _translate("MainWindow", "A1"))
        self.ot2WellComboBox.setItemText(2, _translate("MainWindow", "A2"))
        self.ot2WellComboBox.setItemText(3, _translate("MainWindow", "A3"))
        self.ot2WellComboBox.setItemText(4, _translate("MainWindow", "B1"))
        self.ot2WellComboBox.setItemText(5, _translate("MainWindow", "B2"))
        self.ot2WellComboBox.setItemText(6, _translate("MainWindow", "B3"))
        self.ot2HeightDoubleSpinBox.setPrefix(_translate("MainWindow", "Height: "))
        self.hostnameLineEdit.setPlaceholderText(_translate("MainWindow", "hostname"))
        self.ot2HomePushButton.setText(_translate("MainWindow", " Home OT-2 "))
        self.ot2SendCommandPushButton.setText(_translate("MainWindow", " Send Command:"))
        self.ot2LightsOnPushButton.setText(_translate("MainWindow", "Lights On"))
        self.ot2LightsOffPushButton.setText(_translate("MainWindow", "Lights Off"))
        self.debugClearPushButton.setText(_translate("MainWindow", " Clear Logs "))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.OT2Tab), _translate("MainWindow", "OT-2"))
        self.plateManifestTreeWidget.headerItem().setText(0, _translate("MainWindow", "Plate"))
        self.plateManifestTreeWidget.headerItem().setText(1, _translate("MainWindow", "Well"))
        self.plateManifestTreeWidget.headerItem().setText(2, _translate("MainWindow", "Aninmal"))
        self.PlateFunctionsTab.setTabText(self.PlateFunctionsTab.indexOf(self.ManifestTab), _translate("MainWindow", "Manifest"))
        self.label_23.setText(_translate("MainWindow", "To create a new plate entry, enter the plate ID below and click \"Create\""))
        self.label_24.setText(_translate("MainWindow", "Plate ID:"))
        self.plateIDLineEdit.setPlaceholderText(_translate("MainWindow", "Hydra~XXX-20201231001"))
        self.createPlateButton.setText(_translate("MainWindow", "Create"))
        self.emailLineEdit.setPlaceholderText(_translate("MainWindow", "Enter FROM Email:"))
        self.passLineEdit.setPlaceholderText(_translate("MainWindow", "Enter Password:"))
        self.emailToLineEdit.setPlaceholderText(_translate("MainWindow", "Enter TO Email:"))
        self.sendEmailButton.setText(_translate("MainWindow", "Send Selected"))
        self.label_21.setText(_translate("MainWindow", "SMTP Server:"))
        self.SMTPLineEdit.setPlaceholderText(_translate("MainWindow", "smtp.gmail.com"))
        self.PlateFunctionsTab.setTabText(self.PlateFunctionsTab.indexOf(self.AddPlateTab), _translate("MainWindow", "Add / Email"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.PlateTab), _translate("MainWindow", "Plates"))
        self.label_8.setText(_translate("MainWindow", "Search:"))
        self.searchToolButton.setText(_translate("MainWindow", "..."))
        self.label_19.setText(_translate("MainWindow", "Add New:"))
        self.addStockToolButton.setToolTip(_translate("MainWindow", "New Stock"))
        self.addStockToolButton.setText(_translate("MainWindow", "..."))
        self.addAnimalToolButton.setToolTip(_translate("MainWindow", "New Animal"))
        self.addAnimalToolButton.setText(_translate("MainWindow", "..."))
        self.addColonyToolButton.setToolTip(_translate("MainWindow", "New Colony"))
        self.addColonyToolButton.setText(_translate("MainWindow", "..."))
        self.addEventToolButton.setToolTip(_translate("MainWindow", "New Event"))
        self.addEventToolButton.setText(_translate("MainWindow", "..."))
        self.dataToolButton.setToolTip(_translate("MainWindow", "Animal Data Settings..."))
        self.dataToolButton.setText(_translate("MainWindow", "..."))
        self.databaseTreeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.databaseTreeWidget.headerItem().setText(1, _translate("MainWindow", "Time                    "))
        self.databaseTreeWidget.headerItem().setText(2, _translate("MainWindow", "Location"))
        self.databaseTreeWidget.headerItem().setText(3, _translate("MainWindow", "Population"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.AnimalsTab), _translate("MainWindow", "Animal Data"))
        self.snap_reprocess_button.setText(_translate("MainWindow", "Re-Process"))
        self.scansLabel.setText(_translate("MainWindow", "0"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.SnapTab), _translate("MainWindow", "Snap"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.ControlsTab), _translate("MainWindow", "Camera Controls"))


import media_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
